package nl.pancompany.unicorn.application.domain;

public enum Color {

    RED, BLUE, GREEN, YELLOW, BLACK, WHITE, PURPLE, ORANGE, PINK, BROWN, GRAY,
    BEIGE, TEAL, NAVY, MAROON, OLIVE, PEACH, AQUA, GOLD, SILVER, LIME, CORAL,
    TURQUOISE, INDIGO, VIOLET, MAGENTA, TAN, CYAN, AMBER, JADE, RUBY, EMERALD,
    SAPPHIRE, CREAM, CHARCOAL, BRONZE, MINT, LAVENDER, PLUM, CHOCOLATE, FUCHSIA,
    CRIMSON, IVORY, CHERRY, SLATE, KHAKI, MUSTARD, RASPBERRY, AUBURN, MAUVE, PERIWINKLE
}
